<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SAM.Core">
      <HintPath>..\..\..\SAM\build\SAM.Core.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Core.Rhino">
      <HintPath>..\..\..\SAM\build\SAM.Core.Rhino.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry">
      <HintPath>..\..\..\SAM\build\SAM.Geometry.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry.Rhino">
      <HintPath>..\..\..\SAM\build\SAM.Geometry.Rhino.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SAM_Building\SAM.Core.Building\SAM.Core.Building.csproj" />
    <ProjectReference Include="..\..\SAM_Building\SAM.Geometry.Building\SAM.Geometry.Building.csproj" />
    <ProjectReference Include="..\SAM.Core.Building.Rhino\SAM.Core.Building.Rhino.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RhinoCommon" Version="8.19.25132.1001" />
  </ItemGroup>
</Project>